### ISSUE TITLE
Crash when toggling globe mode 

### ISSUE THREAD

**Issue by paour** [Akylas/alpimaps#8]
Android 2.0.2

If I tap globe icon, the app crashes. I expect Sentry will have reported this.

**Comment by farfromrefug** [comment]
@paour thanks I ll fix it. Sentry is not bundle anymore. Tried to remove all trackers

**Comment by farfromrefug** [comment]
@paour cant reproduce your crash. By any chance could you send me a logcat taken just after the crash?
Thanks

**Comment by paour** [comment]
As usual for JS apps, the logcat is not great, but here goes…

```
MessageQueue callback: handleReceiveCallback
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: com.tns.NativeScriptException: Calling js method onStateChange failed
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: TypeError: Cannot read property 'set' of undefined
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:119)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(SourceFile:103)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(SourceFile:43)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Unknown Source:7)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Unknown Source:1)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.tns.gen.com.swmansion.gesturehandler.OnTouchEventListener.onStateChange(Unknown Source:24)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.j(SourceFile:211)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandler.b(SourceFile:142)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandler.activate(Unknown Source:8)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.TapGestureHandler.onHandle(SourceFile:218)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandler.handle(SourceFile:441)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(SourceFile:109)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(SourceFile:92)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.nativescript.gesturehandler.PageLayout.dispatchTouchEventToOrchestrator(SourceFile:8)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.nativescript.gesturehandler.PageLayout.dispatchTouchEvent(SourceFile:30)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:494)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1894)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at i.m.dispatchTouchEvent(Unknown Source:2)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:452)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:14648)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6443)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6214)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5680)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5737)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5703)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5855)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5711)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5912)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5684)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5737)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5703)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5711)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5684)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8584)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8535)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8433)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8707)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:335)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:183)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:8030)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
03-10 11:19:15.339 25652 25652 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main
```

**Comment by paour** [comment]
Interesting, btw, that NativeScript leverages native libraries designed for React Native :-)

**Comment by farfromrefug** [comment]
@paour you are talking about `com.swmansion.gesturehandler` ? i rewrote a gesturehandler plugin for N based on react native one.
So i have an issue with your crash cant find the real place of the issue as proguard is hiding it. Would you be ok to reproduce it with a debug build? Can share one here

**Comment by paour** [comment]
Gladly. I tried to figure out the build, but I must be missing something…

**Comment by paour** [comment]
> @paour you are talking about `com.swmansion.gesturehandler` ? i rewrote a gesturehandler plugin for N based on react native one.

That's the one, a very well-known RN module.

**Comment by farfromrefug** [comment]
@paour if you want to build i can help you there. There only one tricky thing is that one npm plugin i use a custom version which is not published (not sure i want to yet). But i can show you.
As for the debug build here they are:
[app-arm64-v8a-release](http://gofile.me/4pKGL/n2URm9G3i)
[app-armeabi-v7a-release](http://gofile.me/4pKGL/0s20hruOI)

**Comment by paour** [comment]
Are they really debug builds? They installed over the release build (same signature) and the exception stack is the same (looking back, there wasn't that much obfuscation in the first log).

```
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: com.tns.NativeScriptException: Calling js method onStateChange failed
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: TypeError: Cannot read property 'set' of undefined
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:119)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(SourceFile:103)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(SourceFile:43)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Unknown Source:7)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Unknown Source:1)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.tns.gen.com.swmansion.gesturehandler.OnTouchEventListener.onStateChange(Unknown Source:24)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.j(SourceFile:211)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandler.b(SourceFile:142)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandler.activate(Unknown Source:8)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.TapGestureHandler.onHandle(SourceFile:218)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandler.handle(SourceFile:441)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(SourceFile:109)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(SourceFile:92)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.nativescript.gesturehandler.PageLayout.dispatchTouchEventToOrchestrator(SourceFile:8)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.nativescript.gesturehandler.PageLayout.dispatchTouchEvent(SourceFile:30)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3143)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:494)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1894)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at i.m.dispatchTouchEvent(Unknown Source:2)
03-10 19:26:03.229 27718 27718 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:452)
```

**Comment by farfromrefug** [comment]
@paour indeed my build script was broken. I built another production build but with sentry enabled and JS console enabled. I should get the JS error stack with this build in sentry.
Sorry for the trouble. You can use the same link as before

**Comment by paour** [comment]
Your NAS seems to be disconnected from the Synology reverse proxy thinggy.

<img width="718" alt="SCR-20230313-hyuf" src="https://user-images.githubusercontent.com/90963/224634931-54bcc359-d9f5-4329-a806-855436aac22a.png">

**Comment by farfromrefug** [comment]
@paour my nas is only on from 9am to 1am (France). Sorry about that you must have tried a bit before it started:s
